State.destroy_all

alabama = State.create(name: 'Alabama', abbreviation: 'AL', comment: '')
State.create(name: 'Alaska', abbreviation: 'AK', comment: '')
State.create(name: 'Arizona', abbreviation: 'AZ', comment: '')
State.create(name: 'Arkansas', abbreviation: 'AR', comment: '')
State.create(name: 'California', abbreviation: 'CA', comment: '')
State.create(name: 'Colorado', abbreviation: 'CO', comment: '')
State.create(name: 'Connecticut', abbreviation: 'CT', comment: '')
State.create(name: 'Delaware', abbreviation: 'DE', comment: '')
State.create(name: 'Florida', abbreviation: 'FL', comment: '')
State.create(name: 'Georgia', abbreviation: 'GA', comment: '')
State.create(name: 'Hawaii', abbreviation: 'HI', comment: '')
State.create(name: 'Idaho', abbreviation: 'ID', comment: '')
State.create(name: 'Illinois', abbreviation: 'IL', comment: '')
State.create(name: 'Indiana', abbreviation: 'IN', comment: '')
State.create(name: 'Iowa', abbreviation: 'IA', comment: '')
State.create(name: 'Kansas', abbreviation: 'KS', comment: '')
State.create(name: 'Kentucky', abbreviation: 'KY', comment: '')
State.create(name: 'Louisiana', abbreviation: 'LA', comment: '')
State.create(name: 'Maine', abbreviation: 'ME', comment: '')
State.create(name: 'Maryland', abbreviation: 'MD', comment: '')
State.create(name: 'Massachusetts', abbreviation: 'MA', comment: '')
State.create(name: 'Michigan', abbreviation: 'MI', comment: '')
State.create(name: 'Minnesota', abbreviation: 'MN', comment: '')
State.create(name: 'Mississippi', abbreviation: 'MS', comment: '')
State.create(name: 'Missouri', abbreviation: 'MO', comment: '')
State.create(name: 'Montana', abbreviation: 'MT', comment: '')
State.create(name: 'Nebraska', abbreviation: 'NE', comment: '')
State.create(name: 'Nevada', abbreviation: 'NV', comment: '')
State.create(name: 'New Hampshire', abbreviation: 'NH', comment: '')
State.create(name: 'New Jersey', abbreviation: 'NJ', comment: '')
State.create(name: 'New Mexico', abbreviation: 'NM', comment: '')
State.create(name: 'New York', abbreviation: 'NY', comment: '')
State.create(name: 'North Carolina', abbreviation: 'NC', comment: '')
State.create(name: 'North Dakota', abbreviation: 'ND', comment: '')
State.create(name: 'Ohio', abbreviation: 'OH', comment: '')
State.create(name: 'Oklahoma', abbreviation: 'OK', comment: '')
State.create(name: 'Oregon', abbreviation: 'OR', comment: '')
State.create(name: 'Pennsylvania', abbreviation: 'PA', comment: '')
State.create(name: 'Rhode Island', abbreviation: 'RI', comment: '')
State.create(name: 'South Carolina', abbreviation: 'SC', comment: '')
State.create(name: 'South Dakota', abbreviation: 'SD', comment: '')
State.create(name: 'Tennessee', abbreviation: 'TN', comment: '')
State.create(name: 'Texas', abbreviation: 'TX', comment: '')
State.create(name: 'Utah', abbreviation: 'UT', comment: '')
State.create(name: 'Vermont', abbreviation: 'VT', comment: '')
State.create(name: 'Virginia', abbreviation: 'VA', comment: '')
State.create(name: 'Washington', abbreviation: 'WA', comment: '')
State.create(name: 'West Virginia', abbreviation: 'WV', comment: '')
State.create(name: 'Wisconsin', abbreviation: 'WI', comment: '')
State.create(name: 'Wyoming', abbreviation: 'WY', comment: '')

Comment.create(content: "abc", username: "oscar", state_id: alabama)
Comment.create(content: "def", username: "dick", state_id: alabama)
Comment.create(content: "abcabc", username: "richard", state_id: alabama)
Comment.create(content: "abc123123", username: "ham", state_id: alabama)
Comment.create(content: "abc789789789", username: "king chorizo", state_id: alabama)
